"""
Lending Loop Strategy: base_aave_looper

Supply/borrow leverage loop with state machine and health monitoring

Generated by: almanak strat new
Template: lending_loop
Chain: base
Created: 2026-03-16T18:16:00.603832

Strategy Pattern:
-----------------
1. Inherit from IntentStrategy
2. Use @almanak_strategy decorator for metadata
3. Implement decide(market) method that returns an Intent
4. The framework handles compilation and execution
"""

import logging
from decimal import Decimal  # noqa: F401
from typing import Any, Optional

# Core strategy framework imports
from almanak.framework.intents import Intent
from almanak.framework.strategies import (
    IntentStrategy,
    MarketSnapshot,
    almanak_strategy,
)

logger = logging.getLogger(__name__)


@almanak_strategy(
    name="base_aave_looper",
    description="Supply/borrow leverage loop with state machine and health monitoring",
    version="1.0.0",
    author="Generated",
    tags=["generated", "lending_loop"],
    supported_chains=["base"],
    supported_protocols=["aave_v3"],
    intent_types=["SUPPLY", "BORROW", "REPAY", "WITHDRAW", "HOLD"],
    default_chain="base",
)
class BaseAaveLooperStrategy(IntentStrategy):
    """
    Supply/borrow leverage loop with state machine and health monitoring

    Chain: base
    Protocol: aave_v3

    Configuration Parameters:
    -------------------------
    See config.json for configurable parameters.
    """

    def __init__(self, *args, **kwargs):
        """
        Initialize the strategy with configuration.

        The base class (IntentStrategy) handles:
        - self.config: Strategy configuration (dict or dataclass)
        - self.chain: The blockchain to operate on
        - self.wallet_address: The wallet executing trades
        """
        super().__init__(*args, **kwargs)

        # Helper to get config value from dict or object attributes
        def get_config(key: str, default: Any) -> Any:
            if isinstance(self.config, dict):
                return self.config.get(key, default)
            return getattr(self.config, key, default)

        # Lending parameters
        self.supply_amount = Decimal(str(get_config("supply_amount", "1")))
        self.borrow_amount = Decimal(str(get_config("borrow_amount", "500")))
        self.target_leverage = Decimal(str(get_config("target_leverage", "2.0")))
        self.min_collateral_usd = Decimal(str(get_config("min_collateral_usd", "100")))

        # Token configuration
        self.collateral_token = get_config("collateral_token", "WETH")
        self.borrow_token = get_config("borrow_token", "USDC")

        # State machine: idle -> supplied -> borrowed -> monitoring
        self._loop_state = "idle"

        logger.info(f"BaseAaveLooperStrategy initialized on {self.chain}")

    def decide(self, market: MarketSnapshot) -> Optional[Intent]:
        """
        Make a trading decision based on current market conditions.

        This is the core method of the strategy. It's called by the framework
        on each iteration with fresh market data.

        Parameters:
            market: MarketSnapshot containing:
                - market.price(token): Get current price in USD
                - market.rsi(token, period): Get RSI indicator
                - market.balance(token): Get wallet balance
                - market.chain: Current chain
                - market.wallet_address: Current wallet

        Returns:
            Intent: What action to take
                - Intent.swap(...): Execute a swap
                - Intent.hold(...): Do nothing
                - None: Also means hold
        """
        try:
            # State machine: idle -> supplied -> borrowed -> monitoring
            if self._loop_state == "idle":
                # Check collateral balance
                try:
                    collateral_bal = market.balance(self.collateral_token)
                except ValueError:
                    return Intent.hold(reason="Cannot check collateral balance")

                if collateral_bal.balance_usd < self.min_collateral_usd:
                    return Intent.hold(reason=f"Insufficient {self.collateral_token}")

                logger.info(f"Supplying {self.supply_amount} {self.collateral_token}")
                return Intent.supply(
                    protocol="aave_v3",
                    token=self.collateral_token,
                    amount=self.supply_amount,
                    use_as_collateral=True,
                )

            elif self._loop_state == "supplied":
                # Borrow against collateral
                logger.info(f"Borrowing {self.borrow_amount} {self.borrow_token}")
                return Intent.borrow(
                    protocol="aave_v3",
                    collateral_token=self.collateral_token,
                    collateral_amount=Decimal("0"),
                    borrow_token=self.borrow_token,
                    borrow_amount=self.borrow_amount,
                )

            elif self._loop_state == "borrowed":
                # Swap borrowed tokens back to collateral for loop
                logger.info(f"Swapping {self.borrow_token} -> {self.collateral_token}")
                return Intent.swap(
                    from_token=self.borrow_token,
                    to_token=self.collateral_token,
                    amount="all",
                    max_slippage=Decimal("0.005"),
                )

            elif self._loop_state == "monitoring":
                # Monitor health factor -- would repay if too low
                return Intent.hold(reason=f"Monitoring loop, target_leverage={self.target_leverage}")

            return Intent.hold(reason=f"Unknown state: {self._loop_state}")

        except Exception as e:
            logger.exception(f"Error in decide(): {e}")
            return Intent.hold(reason=f"Error: {str(e)}")

    def get_status(self) -> dict[str, Any]:
        """Get current strategy status for monitoring/dashboards."""
        return {
            "strategy": "base_aave_looper",
            "chain": self.chain,
            "wallet": self.wallet_address[:10] + "..." if self.wallet_address else None,
        }

    def on_intent_executed(self, intent, success: bool, result):
        """Advance state machine after intent execution."""
        if not success:
            return
        intent_type = getattr(intent, "intent_type", None)
        if not intent_type:
            return
        if intent_type.value == "SUPPLY":
            self._loop_state = "supplied"
            logger.info("Supply confirmed -> supplied")
        elif intent_type.value == "BORROW":
            self._loop_state = "borrowed"
            logger.info("Borrow confirmed -> borrowed")
        elif intent_type.value == "SWAP":
            self._loop_state = "monitoring"
            logger.info("Swap confirmed -> monitoring")

    def get_persistent_state(self):
        """Save loop state."""
        return {"loop_state": self._loop_state}

    def load_persistent_state(self, state):
        """Restore loop state."""
        if state:
            self._loop_state = state.get("loop_state", "idle")

    # -------------------------------------------------------------------------
    # TEARDOWN (required) - implement so operators can safely close positions
    # Without these methods, operator close-requests are silently ignored.
    # See: blueprints/14-teardown-system.md
    # -------------------------------------------------------------------------

    def supports_teardown(self) -> bool:
        """Indicate this strategy supports safe teardown."""
        return True

    def get_open_positions(self):
        """Return all open positions for teardown preview."""
        from datetime import UTC, datetime

        from almanak.framework.teardown import (
            PositionInfo,
            PositionType,
            TeardownPositionSummary,
        )

        positions = []

        if self._loop_state in ("borrowed", "monitoring"):
            positions.append(
                PositionInfo(
                    position_type=PositionType.BORROW,
                    position_id="base_aave_looper_borrow",
                    chain=self.chain,
                    protocol="aave_v3",
                    value_usd=Decimal("0"),  # Will be enriched by framework
                    details={
                        "borrow_token": self.borrow_token,
                        "borrow_amount": str(self.borrow_amount),
                    },
                )
            )

        if self._loop_state in ("supplied", "borrowed", "monitoring"):
            positions.append(
                PositionInfo(
                    position_type=PositionType.SUPPLY,
                    position_id="base_aave_looper_supply",
                    chain=self.chain,
                    protocol="aave_v3",
                    value_usd=Decimal("0"),  # Will be enriched by framework
                    details={
                        "collateral_token": self.collateral_token,
                        "supply_amount": str(self.supply_amount),
                    },
                )
            )

        return TeardownPositionSummary(
            strategy_id=getattr(self, "strategy_id", "base_aave_looper"),
            timestamp=datetime.now(UTC),
            positions=positions,
        )

    def generate_teardown_intents(self, mode=None, market=None) -> list[Intent]:
        """Generate intents to close all positions.

        Teardown goal: Repay borrows, withdraw collateral, swap to quote

        Priority order: repay borrow first (frees collateral), then withdraw.
        """
        from almanak.framework.teardown import TeardownMode

        intents: list[Intent] = []
        max_slippage = Decimal("0.03") if mode == TeardownMode.HARD else Decimal("0.005")

        # 1. Repay borrow (if active)
        if self._loop_state in ("borrowed", "monitoring"):
            intents.append(
                Intent.repay(
                    protocol="aave_v3",
                    token=self.borrow_token,
                    amount="all",
                )
            )

        # 2. Withdraw collateral (if supplied)
        if self._loop_state in ("supplied", "borrowed", "monitoring"):
            intents.append(
                Intent.withdraw(
                    protocol="aave_v3",
                    token=self.collateral_token,
                    amount="all",
                )
            )

        # 3. Swap collateral back to stable if needed
        if self._loop_state != "idle":
            intents.append(
                Intent.swap(
                    from_token=self.collateral_token,
                    to_token=self.borrow_token,
                    amount="all",
                    max_slippage=max_slippage,
                )
            )

        return intents


if __name__ == "__main__":
    print("=" * 60)
    print("BaseAaveLooperStrategy")
    print("=" * 60)
    print(f"Strategy Name: {BaseAaveLooperStrategy.STRATEGY_NAME}")
    print(f"Supported Chains: {BaseAaveLooperStrategy.SUPPORTED_CHAINS}")
    print(f"Supported Protocols: {BaseAaveLooperStrategy.SUPPORTED_PROTOCOLS}")
    print(f"Intent Types: {BaseAaveLooperStrategy.INTENT_TYPES}")
    print("\nTo run this strategy:")
    print("  uv run almanak strat run --once")
